spring:
  application:
    name: spring-board
  config:
    import: ./config.yml
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    encoding:
      charset: utf-8
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

file:
  upload:
    path: ${upload.profile-path}
    board-path: ${upload.board-path}