spring:
  application:
    name: spring-board
  config:
    import: ./config.yml
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    encoding:
      charset: utf-8
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com # 지메일을 이용해서 메일 발송하기
    password: ${mail.password} # config.yml 에서 비밀번호를 전달
    username: ${mail.username}
    # 자바로 메일보내기가 내부적으로 java.mail 로 만든 기능 사용 그 설정값을 우리가 직접 넘겨줌
    # spring 부트가 기본적으로 메일보낼 때 세팅을 해놓은 것을 우리회사 입맛대로 교체
    properties:
      mail:
        smtp:             # smtp -> SMTP 변경 하지만 소문자 정답 대문자로 작성하면 변수명오류 인증 오류
          auth: true      # SMTP 서버에 아이디/비밀번호 로그인 허용
          starttls:       # starttls -> 오타: 단어 'starttls' 내  소문자 맞음
            enable: true  # 암호화 처리에서 지메일로 전달하겠다. *TLS
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
file:
  upload:
    path: ${upload.profile-path}
    board-path: ${upload.board-path}

# config 작성한 변수이름
# application 작성한 변수이름 동일
# 현재 상황에서는
#jwt.secret을 두분 선언한것과 같기 때문에
# config에 작성하는 변수 이름과
# application에 작성하는 변수이름 달라야한다.
jwt:
  secret: ${jwt.config.secret}
  access-expiry: 1800000      # 30분 (ms)
  refresh-expiry: 1209600000  # 14일 (ms)



