db:
  url: jdbc:mysql://localhost:3306/mydb
  username: root
  password: tjee1234

upload:
  profile-path: C:/uploads/profile
  board-path: C:/uploads/board

mail:
  username: your-email@gmail.com
  password: your-app-password
jwt:
    secret: springboard-jwt-secret-key-2026-change-this-please!!!


























